name: icms_pro_app
description: App Flutter completo de ICMS com login por PIN, splash, ícone, histórico e pronto para Codemagic.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  package_info_plus: ^8.0.2
  share_plus: ^10.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_native_splash: ^2.4.1
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/data/icms.json
    - assets/icons/app_icon.png

# Splash config (flutter_native_splash)
flutter_native_splash:
  color: "#ffffff"
  color_dark: "#121212"
  image: assets/icons/app_icon.png
  android: true
  ios: false
  android_12:
    image: assets/icons/app_icon.png
    icon_background_color: "#ffffff"
    icon_background_color_dark: "#121212"

# App icon config (flutter_launcher_icons)
flutter_icons:
  android: true
  ios: false
  image_path: assets/icons/app_icon.png
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: assets/icons/app_icon.png
