name: icms_pro_app
description: Aplicativo ICMS Pro
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.6

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/icons/app_icon.png"

flutter_native_splash:
  color: "#ffffff"
  image: assets/icons/app_icon.png
  android: true
  ios: false


 
